### ISSUE TITLE
Snikket is not found

### ISSUE THREAD

**Issue by Neustradamus** [snikket-im/snikket-ios#1]
On Apple Store for iOS, Snikket is not found.

It is blocked?

**Comment by mwild1** [comment]
![no-releases](https://user-images.githubusercontent.com/24315/103474515-8b2ab180-4d9c-11eb-8402-236e2102a505.png)


Please stop spamming issue trackers with things that are not actually issues. Stop punishing open-source developers for developing code openly. We have enough to deal with already.
