### ISSUE TITLE
User Session terminated

### ISSUE THREAD

**Issue by MuhammedAnasm4444** [snikket-im/snikket-ios#104]
**Describe the bug**
Recently I got a error that like "User session terminated"

what was this about??

**Comment by mwild1** [comment]
Hi, thanks for the report. This error text does not appear to be from any component of Snikket. So... I don't know what it is about. If you can provide more information that suggests a problem with Snikket, feel free to do so.

**Comment by MuhammedAnasm4444** [comment]
I think it was causing because I logged the same account on both iOS and android clients, I am not sure 100% but I think this is the cause. But really don't know the root cause
