### ISSUE TITLE
Timestamp errors on some messages

### ISSUE THREAD

**Issue by inuit-lang** [snikket-im/snikket-ios#107]
**Describe the bug**
In encounter timestamp errors on some received messages, they are associated with the wrong time (usually 3-4 hours before the real time) and can even be displayed in the wrong order with those I send, who have the right time.

This bug occurs occasionally, not every time 

**Screenshots**
![snikket-timestamp](https://user-images.githubusercontent.com/75372212/133974017-5f4050b8-455b-400e-b116-11d84112f88c.jpg)

On this screenshot, the message from above is an answer to the photo

**Software versions:**
 - App Version: 1.1
 - iOS version: 12.5.4
 - iPhone model: iPhone 5s

 - Server software: ejabberd 21.01-2

My contacts use Conversations and are on the same server than me.

**Comment by mwild1** [comment]
Hi, thanks for the report!

Is your server your own? Do you know if the server's clock is incorrect, or in a specific timezone? And is that timezone different to the one configured on your device?

**Comment by inuit-lang** [comment]
Yes this server is my own, but after a little investigation it appears that this issue also occurs with other clients than Snikket.
However, it seems to have appeared at the same time as I started using Snikket.

The system date of the server is correct and is set to Paris timezone, as well as my devices.

Now I don't exclude a server side error, but I would be very strange as I didn't change it's config for a long time and I never had this issue before

**Comment by mwild1** [comment]
Thanks for the additional info. I'm closing this for now, as it seems to affect other clients and you're not using a Snikket server. Nobody else has reported this issue in the meantime, so it's probably something specific to your server. Good luck!
