### ISSUE TITLE
Previously Detroyed MUC Re-Appears in UI and Freezes Siskin

### ISSUE THREAD

**Issue by Ged296123** [snikket-im/snikket-ios#11]
**Describe the bug**
Occassionally (not always) previously destroyed MUC reappears in UI. In this case, app tries to join destroyed MUC and freezes.

**To Reproduce**
1. Start app. 
2. On occasion (not always, unfortunately cannot re-produce this state), MUC that was destroyed in the past re-appears in UI. 
3. If above state occurs, Siskin tries to join destroyed MUC and freezes or if I try to delete MUC with swipe gesture, app freezes. If above state does not occur, app runs normally as before. 
4. Have to reset app to be able to use it again.

**Expected behavior**
A destroyed MUC should not be seen in UI, app should not freeze when this happens.

**Screenshots**
N/A

**Details (please complete the following information):**
 - Siskin Version: 6.2
 - iOS version: 14.4
 - iPhone model: iPhoneX

**Additional context**

**Comment by Ged296123** [comment]
Appologies; accidentally reported bug for another bug. Cannot remove my entry, admin kindly requested to delet.

**Comment by mwild1** [comment]
Upstream issue is https://github.com/tigase/siskin-im/issues/98
