### ISSUE TITLE
Group search not working properly

### ISSUE THREAD

**Issue by hashilsemin** [snikket-im/snikket-ios#121]
In the Join group View controller it doesn't show full list of  group. My XMMP server has 250+ groups but it only shows around 100 groups.
But if I type the full group name and type search it shows.

**Comment by mwild1** [comment]
Hi, thanks for the report. Are you using the app with a Snikket server?

Can you give an example of what you type, and a group name that was not matched that should be?

**Comment by hashilsemin** [comment]
no the xmpp server is not snikket.
does it limit the size of the number of group loading at initial state?

**Comment by mwild1** [comment]
You didn't say what server software you are using, but it sounds like it is probably ejabberd, which has a default limit of 100 results when querying for MUC rooms.

You can override it with the `max_rooms_discoitems` option:

```                                                                                                                                     
modules:
  mod_muc:
    max_rooms_discoitems: 10000
```

For further ejabberd support questions see https://www.ejabberd.im/support/index.html
