### ISSUE TITLE
Message input area not scrollable

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-ios#129]
**Describe the bug**
When a long multiline message is typed, it's not possible to see the last lines of the message. Ideally it should be possible to scroll the text up and down when there is a lot of unsent text in the input area.

**To Reproduce**
1. In Settings->Chats ensure "Send message on return" is off
2. Open a chat and keep entering lines of text until the input box fills the screen
3. Enter more lines of text. The cursor and the end lines are no longer visible, and it is not possible to scroll them into view.

**Software versions:**
 - App Version: 1.2 (4)
 - iOS version: 14
 - iPhone model: iPhone SE 1st gen (manages 10 lines, larger screens can manage more but have the same issue eventually)

**Comment by Hund** [comment]
My sister have this issue with version 1.2.1.
