### ISSUE TITLE
Use monospace font for codeblocks

### ISSUE THREAD

**Issue by mdosch** [snikket-im/snikket-ios#14]
If you use ` ``` ` for codeblocks snikket-android shows the codeblock in a monospace font. Snikket-ios should do the same. Compare the screenshots of snikket-ios and conversations (same behavior as snikket-android).

![3A97E509-B287-4C5D-AB86-C7C97B2DB02E](https://user-images.githubusercontent.com/5103003/108832671-23d6f400-75cc-11eb-9a9f-0322d03d9fef.jpg)

![Screenshot_20210223-114241_Conversations](https://user-images.githubusercontent.com/5103003/108832969-7b755f80-75cc-11eb-8c63-2718e1db3d21.png)

**Comment by mimi89999** [comment]
Works if you enable markdown experimental support.

**Comment by mwild1** [comment]
Thanks for the report. I'm going to close this in favour of #33 which I just created to track XEP-0393 support.
