### ISSUE TITLE
How to enable group chat push notifications?

### ISSUE THREAD

**Issue by gertyq** [snikket-im/snikket-ios#145]
I have some questions about Push notifications implemented in Snikket. I have prosody server and before 30 Sep all iOS clients were ChatSecure. All push notifications (1:1 chats and group chats) worked. But I noticed that ChatSecure is not supported now (also because push notifications don't work) and tell all iOS users to delete ChatSecure and install Snikket. Now push notifications work but only in 1:1 chats. What should I change in prosody configuration or tell to change Snikket users in the app for enabling group chat push notifications?

What I understand now:

- When the users that are the members of persistent MUC are offline (not in the room) push notifications should not be sent. This can be fixed by using `mod_muc_offline_delivery`, but for now we don't need this feature, we just need receiving pushes when the user in the room.
- When the user closes the app by _swiping_ (or how this calls) he goes to offline and push notifications will be deregistered. If the app closed by OS then push notifications will not be deregistered. It is normal behavior and if the user want to receive pushes from the Snikket he shouldn't close the app forcibly.
- So if the user didn't close the app and the new message in persistent MUC where he is a member has been sent by someone in the room then the push registration is enabled and the server should send push to `push-ios.snikket.net` which should send to iOS device.

But it doesn't. In all cases it is something like:
```
Oct 26 13:22:41 c2s14c6268	debug	Received[c2s]: <message to='MUC' id='90b2bf1c-4d8c-44a2-85d5-3ee381064789' type='groupchat'>
Oct 26 13:22:41 c2s14c6268	debug	Not archiving stanza: <message to='MUC' id='90b2bf1c-4d8c-44a2-85d5-3ee381064789' from='sender' type='groupchat'> (type)
Oct 26 13:22:41 xmpp_server:mam	debug	Not archiving stanza: <message to='member_who_away' id='90b2bf1c-4d8c-44a2-85d5-3ee381064789' from='MUC/sender_nickname' type='groupchat'> (type)
Oct 26 13:22:41 c2s152e350	debug	Sending[c2s]: <message to='member_who_away' id='90b2bf1c-4d8c-44a2-85d5-3ee381064789' from='MUC/sender_nickname' type='groupchat'>
Oct 26 13:22:41 c2s152e350	debug	hibernating since 2021-10-26T09:12:55Z, stanza queued
Oct 26 13:22:41 c2s152e350	debug	NOT invoking cloud handle_notify_request() for newly smacks queued stanza (session.push_identifier is not set: <nil>)
```
So as I see there _hibernating_ state doesn't cause sending pushes. In 1:1 chats it cause.
I was trying to load `mod_muc_cloud_notify` under the global modules_enabled list, under the MUC component list and under both lists but in all these 3 cases after restarting prosody and re-registering pushes on clients nothing changes. Although as I mentioted above ChatSecure app was able to send pushes with this config earlier.

All Snikket clients have inactive toggle `Push notifications` in group chat settings:

![push1](https://user-images.githubusercontent.com/92697815/138854847-7807b488-9599-4a08-b3ff-4ad7c5f77fe0.png)

Also in account/server settings all Snikket clients have `When in Away/XA/DND state` toggle inactive:

![push2](https://user-images.githubusercontent.com/92697815/138854707-6fd9e9df-a1f5-445e-8da8-9effd0ebe9a0.png)

Is it normal? And in some cases one of Snikket iOS clients stay Available even when _hibernating_ although another clients stay Away (as far as I understand is expected) - is it wrong app/iOS config or it is normal and it happens sometimes?

`prosodyctl about` output:
```
Prosody 0.11.10

# Prosody directories
Data directory:     /var/lib/prosody
Config directory:   /etc/prosody
Source directory:   /usr/lib/prosody
Plugin directories:
  /opt/prosody-modules/ - prosody-modules rev: 71bec9c21dcd
  /usr/lib/prosody/modules/
  

# Lua environment
Lua version:             	Lua 5.2

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/share/lua/5.2/?.lua
  /usr/share/lua/5.2/?/init.lua
  /usr/lib/lua/5.2/?.lua
  /usr/lib/lua/5.2/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/lib/lua/5.2/?.so
  /usr/lib/lua/5.2/loadall.so

LuaRocks:        	Not installed

# Network

Backend: select

# Lua module versions
lfs:     	LuaFileSystem 1.8.0
lxp:     	LuaExpat 1.3.0
socket:  	LuaSocket 3.0-rc1
ssl:     	1.0.2
```

**Comment by tpikonen** [comment]
Thanks a lot for this thorough explanation. Apparently the group chat notifications still do not work in snikket-ios but this issue is closed. Is there an open bug somewhere, so that I can test this feature when it's closed?

**Comment by mwild1** [comment]
We're working on a new server release, it should be published this week. It will be announced on the [Snikket blog](https://snikket.org/blog/), [Mastodon](https://fosstodon.org/web/@snikket_im) and [Twitter](https://twitter.com/snikket_im).

**Comment by gertyq** [comment]
Thanks for your efforts. What should be done to make pure prosody-stable compatible with this feature if it is possible?

**Comment by mwild1** [comment]
@tpikonen In case you missed it, the release is now available: https://snikket.org/blog/nov-2021-server-release/

@gertyq Prosody 0.11.x cannot work with this because a [core change was required](https://hg.prosody.im/trunk/rev/df1d3df2204a). This change will be in Prosody 0.12 which we hope to release "soon" (coming weeks/months, as time allows). Apart from that change, the MUC service needs [mod_muc_offline_delivery](https://modules.prosody.im/mod_muc_offline_delivery) and the user's host needs [mod_cloud_notify_extensions](https://modules.prosody.im/mod_cloud_notify_extensions). There are also two Snikket-specific modules, [mod_snikket_client_id](https://github.com/snikket-im/snikket-server/blob/master/snikket-modules/mod_snikket_client_id/mod_snikket_client_id.lua) and [mod_snikket_ios_preserve_push](https://github.com/snikket-im/snikket-server/blob/master/snikket-modules/mod_snikket_ios_preserve_push/mod_snikket_ios_preserve_push.lua) - these work around some issues I discovered recently that affect all Siskin and Snikket pushes from Prosody in certain edge cases. Unfortunately they are a bit hacky, and specific to the Snikket iOS client, which is why they are not in prosody-modules like the others. I want to develop a standard cross-client solution in Prosody and the app, hopefully by early next year (but releasing Prosody 0.12 takes priority for now). Hope this helps!

**Comment by tpikonen** [comment]
Thanks again for your work. I'm also interested in this feature in pure Prosody. Did I understand correctly that Snikket-IOS group chat push notifications will not work on Prosody version 0.12, but maybe on 0.13?

**Comment by mwild1** [comment]
@tpikonen they will work in 0.12 with the necessary supporting modules (which will not be included by default, but will be easily installable). You can try this today with Prosody trunk nightly builds for example.

**Comment by gertyq** [comment]
Thanks, is it possible to build trunk version for arm?

**Comment by mwild1** [comment]
Yes, Prosody trunk packages are built for ARM on Debian/Ubuntu. See https://packages.prosody.im/debian/

**Comment by gertyq** [comment]
I have converted deb package to alarm and after solving several dependency problems, I was finally able to run it with all modules mentioned above.
It works! Now group chat notifications via `muc_offline_delivery` successfully invoke for every member who hasn't Available status. But there are two problems: Snikket UI has strange behaviour: after enabling "Group chat notifications" toggle it becomes inactive. The second problem: after enabling `mod_cloud_notify_encrypted` every push notification fails with the error:
```
Traceback[c2s]: ...od_cloud_notify_encrypted/mod_cloud_notify_encrypted.lua:127: bad argument #2 to 'final' (string expected, got light userdata)
	stack traceback:
	[C]: in method 'final'
	...od_cloud_notify_encrypted/mod_cloud_notify_encrypted.lua:127: in field '?'
	/usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
	(...tail calls...)
	/opt/prosody-modules/mod_cloud_notify/mod_cloud_notify.lua:385: in upvalue 'handle_notify_request'
	/opt/prosody-modules/mod_cloud_notify/mod_cloud_notify.lua:569: in field '?'
	/usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/lib/prosody/modules/mod_mam/mod_mam.lua:447: in field '?'
	/usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
	(...tail calls...)
	/usr/share/lua/5.4/prosody/core/stanza_router.lua:188: in upvalue 'core_post_stanza'
	/usr/share/lua/5.4/prosody/core/stanza_router.lua:128: in upvalue 'core_process_stanza'
	/usr/lib/prosody/modules/mod_c2s.lua:322: in upvalue 'func'
	/usr/share/lua/5.4/prosody/util/async.lua:127: in function </usr/share/lua/5.4/prosody/util/async.lua:125>
```
At this time I have disabled this module and all we need works now. Thank you for your efforts and good luck with the next stage of your work.

**Comment by mwild1** [comment]
> Snikket UI has strange behaviour: after enabling "Group chat notifications" toggle it becomes inactive

Ensure you have a recent (within the past ~2 weeks) trunk nightly build of Prosody, and add this option under the `Component` line for your MUC service:

```
muc_registration_include_form = true
```

> after enabling mod_cloud_notify_encrypted every push notification fails with the error:

I really can't explain this one. It says a `light userdata` (a pointer-like object that Lua modules written in C can create) is being passed instead of a string. However the value it is complaining about (`push_json`) comes from Prosody's `util.json` library, which definitely returns a string.

**Comment by gertyq** [comment]
> muc_registration_include_form = true

After enabling this option the toggle doesn't work as expected but we have faced strange behavior on Snikket-iOS devices:
Tap on the toggle causes leaving the room and after closing/opening the app this room disappears from the conversations list

And one more strange thing has been going on for the last week in group chats: 
Sending from Snikket-iOS for another Snikket-Android viewing is always good
Sending from Snikket-Android for another Snikket-Android viewing is always good
Sending from Snikket-Android for another Snikket-iOS viewing is always good
Sending from Snikket-iOS for another Snikket-iOS viewing is good only if both accounts/devices are online, but if viewing device is offline then push notification is successfully sent **but** when the app is opened again this offline message looks like: 
![wrong_offline_message](https://user-images.githubusercontent.com/92697815/145214417-39d3c81c-4c46-4ef0-87f6-5ad19025b80c.png)
After that if both devices are online the messages between them are seen good again. Unloading `muc_offline_delivery` turns off group chat pushes but this behavior remains. Loading/unloading `cloud_notify_*` modules doesn't change anything. Personal communication is good in any cases so I think it somehow related to archiving offline messages in group chats for or from iOS devices.
