### ISSUE TITLE
Tap targets too small for attachments in compose window

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#16]
The tap targets for the various attachment icons to the right of the compose window are too small. Apple recommends 44x44pts for button touch targets. While this might make the attachment icons overcrowd the input field they are commonly put behind a single attachment button (usually a plus or paperclip icon).

**Comment by mimi89999** [comment]
I wrote about it in https://github.com/snikket-im/snikket-ios/issues/5
> The send buttons might be too small

**Comment by distefam** [comment]
[Glyphish](https://www.glyphish.com/) icons are commonly used by iOS developers but there are others as well.
