### ISSUE TITLE
Crash report: specialized Array.remove(at:) + 140

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-ios#163]
**Describe the bug**
The app crashes in XMPPService.swift `fetchEnded()` while calling `self.fetchingFor.remove(at: idx)`

**To Reproduce**
Unknown - TestFlight feedback suggests no user interaction is necessary.

**Software versions:**
 - App Version: 1.2 (8)
 - iOS version: Reported across iOS 12, 14 and 15
 - iPhone model: All reports have been on iPhones, e.g. iPhone 12 mini running iOS 15.

**Branch**

Please make a new branch from master for this fix: `fix/fetchended-crash`

**Comment by khaliddd** [comment]
@mwild1 I was not able to reproduce the crash, any more information about this would be helpful.

**Comment by mwild1** [comment]
I just analysed crash reports from 1.2 build 9, which included [fff7d76](https://github.com/snikket-im/snikket-ios/commit/fff7d76e69e3f5bfaeca9983745eff98f66d13fa) - it looks like it has indeed solved the issue!
