### ISSUE TITLE
Adding attachment to messages doesn't work when running Snikket on an Apple Silicon Mac

### ISSUE THREAD

**Issue by jeromatron** [snikket-im/snikket-ios#180]
I've installed Snikket on MacOS though it says it's the iPad version of the app.  I'm impressed at how well it works.  However, adding an attachment doesn't seem to work.  I click on the + next to the chat and it doesn't appear to do anything.  I'm not sure where to find the logs but I'm happy to dig a bit more or install a dev build or something to get more underlying details.
I'm guessing there are slight differences in file selection between the Mac and iPad's way of doing it.  For example, if I try to select an avatar photo on the mac, it goes directly to my photos library instead of a file selector which makes sense.  The + would probably go to a more general file selector though.

**Comment by mwild1** [comment]
Hi, thanks for the report!

You didn't say what version of the app you are using. Due to the similarity of your issue to https://github.com/snikket-im/snikket-ios/issues/111, if you're not currently using beta builds but would be up for that, could you please test whether this issue occurs in the [latest beta build](https://snikket.org/app/ios/) published on TestFlight?

**Comment by jeromatron** [comment]
I'm using version 1.1, but I'll register for the beta builds now and give it a go.  Thanks!

**Comment by jeromatron** [comment]
Hmm, I installed TestFlight on my Mac but when going to the Snikket 1.2 page it says it can only be tested on an iOS device.  It looks like that's been seen in other communities as well.
https://www.reddit.com/r/ApolloAppBeta/comments/qmsp2q/testflight_beta_for_apple_silicon_macs/

**Comment by jeromatron** [comment]
I'll give both the current version (1.1) and the beta version (1.2) with the fix for #111 on an iPad and see how that goes.

**Comment by jeromatron** [comment]
I was able to reproduce it crashing on an iPad Pro (version 1.1) and that it works properly with 1.2.  So hopefully that will address the mac issue as well.  Once 1.2 is released, I can try it on the mac.  That's probably the best way to move forward with this.  Thanks!

**Comment by jeromatron** [comment]
I verified that I can add an attachment with version 1.2 on my apple silicon mac.  One interesting thing is that when I double click on an image attachment after I've sent it, a menu appears at the + sign.  Also if I right click it, it gives me options to preview it (which doesn't really let me preview it).  Other than that, it's great to be able to attach stuff now!
