### ISSUE TITLE
Preauthed registration flow hangs on second account

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-ios#2]
**Describe the bug**

When registering an additional account, the registration dialog is not dismissed even on successful registration.

**To Reproduce**
1. Have an account in the app
2. Open a preauth URI, accept the prompt and enter username/password for the new account
3. Tap 'Register'
4. Spinner appears and account is registered, but the dialog and spinner remain with no way to dismiss.

**Expected behavior**
On successful registration the dialog should close, regardless of whether this is the first account or not.

**Details (please complete the following information):**
 - Snikket version: 1.0 (5)
 - Branch: master
 - iOS version 14.2
 - iPhone model iPhone SE 1st Gen

**Additional context**

One hint at what might be going wrong: when registering the first account, the registration dialog has a white header. On registration of a second account it has a yellow header. There seem to be two registration dialogs?

**Comment by hantu85** [comment]
The applied fix should solve this issue

**Comment by mwild1** [comment]
Just tested. Works great now, thank you!
