### ISSUE TITLE
Visually distinguish between sent and received messages

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#21]
There are many ways to handle this, the most common being colored chat bubbles. Most, if not all, messaging apps have the avatar beside sent and received messages be on opposite sides of the screen as well.

Right now, it is very difficult to at-a-glance distinguish between sent and received messages.

**Comment by mimi89999** [comment]
Maybe https://github.com/MessageKit/MessageKit could me used for conversation view?
