### ISSUE TITLE
Pull-to-refresh is non-standard for iOS

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#22]
iOS has a built-in pull-to-refresh mechanism that is activated by pulling down in a list view. This displays a standard animated spinner at the top of the list view, though that can be customized to be a flying Snikket (see Twitter's flying bird animation) for example.

Snikket currently activates pull-to-refresh by swiping up in the list view. This is non-standard and unexpected.

Also, when pulling to refresh it pulls in old messages that may have been encrypted for a previous device. This leads to a host of OMEMO error messages showing up in one's history.

**Comment by mimi89999** [comment]
When you pull/scroll up you access old messages from MAM. That's expected. There is no need to refresh the conversation view because new messages are automatically displayed when received. XMPP does not have periodic pulling unlike some protocols.

**Comment by distefam** [comment]
@mimi89999 the issue isn't that the resulting behavior upon refresh isn't expected it is that the direction and interface of the pull-to-refresh is non-standard. Also, the OMEMO errors.
