### ISSUE TITLE
OMEMO doesn't work in MUC with the iOS client

### ISSUE THREAD

**Issue by Hund** [snikket-im/snikket-ios#228]
## Describe the bug

My partner and my sister are both using Snikket on iOS, the rest is using Android or any regular computer. When my sister activates OMEMO, my partner can't see my sisters messages. Everyone can see my partners messages with OMEMO enabled though, including my sister. I have looked around in the client for iOS, but it doesn't seem like there's any settings for anything. 

Also. When my girlfriend enabled OMEMO in the MAM, she (read: the client) sent a messages to all her contacts, and all the contacts sent two messages back. The message they all sent and recieved was this:

> Message was not encrypted for this device.

It should be noted that all my family members only have a single device each, with only one client (Snikket).

**Edit:** And it now stopped working for my sister as well. She can't see the messages our mom (using Conversations on Android) sends, but she could see my messages, who's also using Conversations.

## To Reproduce

Steps to reproduce the behavior: Enable OMEMO.

### My partner

* App Version: 1.2
* iOS version: 17.1.2
* iPhone model: iPhone 13 Mini

### Server

* Snikket (Beta)

What's wrong? And is there's something they can do? Other than throwing away their shit iPhones. :D

**Comment by Hund** [comment]
My client have now sent two of these messages to my partner. I haven't sent here any messages myself and she haven't sent any messages to me either.

OMEMO is working fine for private chats. I don't know why it started spamming these messages now.

**Comment by stillgreenmoss** [comment]
i experienced this same issue in an all-iOS MUC with self-hosted snikket. it was the only significant issue we ran into, and it was unfortunately a total showstoppper because since it's on the client there's no obvious path to debugging it. this specific issue is what caused us to have to stop using snikket.

**Comment by mwild1** [comment]
I believe this to be fixed in the latest release of the app (1.2.1) and server (February release). Thanks to everyone who helped with debugging!

**Comment by Hund** [comment]
I can confirm that it's not fixed yet. My sister is using version 1.2.1 on iOS, and we're using server version `stable-20240221`.
