### ISSUE TITLE
Remove confusing settings that can break expected Snikket behavior

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#24]
Right now, Snikket simply toggles settings in the UI to defaults that make Snikket work as expected. Users can, however, still go in and change these settings, which can break expected functionality, not to mention confuse users.

The following settings panels should be **removed** from the main 'Settings' page:

- [ ] Notifications (only option is "Notifications from unknown", which should be always enabled)
- [ ] Experimental (bookmarks sync should always be enabled, the other options should always be disabled)

On the 'Media' page, **remove**:

- [ ] "File sharing via HTTP" (should be always enabled)

On the 'Chats' page, **remove**:

- [ ] "Message carbons" (should be always enabled)

*Issue description edited by MattJ*

**Comment by mwild1** [comment]
I just edited the issue description to reflect the immediate changes we should make. For the record I removed the following items from the list:

- Request delivery receipts (perhaps rename to something more generally understandable)
- Settings > Contacts (entire screen except for blocked contacts perhaps)

I think these are both less clear than a simple removal and needs extra planning (e.g. figuring out some parity with the Android app).
