### ISSUE TITLE
Calls drop immediately when calling from iOS

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#26]
**Describe the bug**
When calling from Snikket iOS to Snikket Android calls immediately drop when Android picks up the phone.

**To Reproduce**
1. Initiate a call from Snikket iOS to a contact who is on Snikket Android
2. Pick up the call from Snikket Android
3. Observe that Snikket iOS drops the call immediately
4. Observe that Snikket Android still thinks it is on a call

**Expected behavior**
The call should connect.

**Additional context**
Potentially related to #17

**Comment by distefam** [comment]
Calling from Android to iOS using the same devices and accounts works as expected.

**Comment by mimi89999** [comment]
Probably a STUN/TURN issue. Are both devices in the same network?

**Comment by distefam** [comment]
I have tried it with devices on the same local network and also with devices on entirely different networks. The issue is present in both scenarios.

**Comment by mwild1** [comment]
@distefam still can't reproduce this issue. Can you still reproduce it on the latest version of both apps? This issue has also not been reported by anyone else, which makes me suspect it's an issue with your setup (e.g. STUN/TURN), or specific app versions or maybe even devices.

It would still be good to know what though...

**Comment by distefam** [comment]
I have not seen this issue in a long time and I have made many such calls. It was probably a version mismatch as you said. I think it makes sense to close this and see if it gets reported again.

**Comment by mwild1** [comment]
That's great news, thanks for the confirmation!
