### ISSUE TITLE
Distinguish quoted text in messages

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#27]
Android displays quoted messages with a solid bar in the left margin of the text that is being quoted. iOS, however, simply displays a `>` character to the left of the quote, which is unclear to all users who do not understand markdown.

**Comment by mwild1** [comment]
Thanks for the report! Closing this in favour of #33 which I created to track support for message styling (XEP-0393). This is the standard the Android app is using to format messages.
