### ISSUE TITLE
Calls only play through phone loudspeaker

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#28]
**Describe the bug**
Calls on iOS only play through the phone's loudspeaker (speaker phone).

**To Reproduce**
1. Initiate or receive a call on iOS
2. Observe that the call comes through the loud speaker and that there is no mechanism to switch it to the earpiece

**Expected behavior**
Non-video calls should default to using the earpiece speaker, which is standard behavior for the built-in phone calling application as well as every other VoIP application. There could be a button to toggle loud and regular earpiece speakers while on a call.

**Comment by Krishnadevi9878** [comment]
Nice

**Comment by mwild1** [comment]
Got confirmation that this will hopefully be worked on soon, upstream.

**Comment by mwild1** [comment]
Upstream issue is https://github.com/tigase/siskin-im/issues/56
