### ISSUE TITLE
Share mutliple pictures/files at once

### ISSUE THREAD

**Issue by sonicnkt** [snikket-im/snikket-ios#30]
The current iOS Version does not seem to support selecting multiple pictures or files to share at once so if you want to transfer multiple files you have to do the share dialog for every single file again which makes this quite complicate and time consuming.

**Describe the solution you'd like**
In the file selection menu add an option to select multiple files/pictures for sharing.

![grafik](https://user-images.githubusercontent.com/5454622/123538927-63a71700-d737-11eb-8228-f3913da2e7b0.png)

**Comment by mwild1** [comment]
Thanks for the report! We're tracking support for this feature in https://github.com/snikket-im/snikket-ios/issues/15
