### ISSUE TITLE
Share location and show "geo:" links

### ISSUE THREAD

**Issue by mdosch** [snikket-im/snikket-ios#45]
In Conversations and Snikket Android you can share your location, it would be nice if Snikket iOS would also support this.
There is also an request for Siskin: https://github.com/tigase/siskin-im/issues/44

**Comment by mwild1** [comment]
**Requirements**
- Sharing a location from the Android app should display in the iOS app as either an embedded map (preferable) or a button/icon to open the location in a maps app.
- It should be possible to share a location in the iOS app, and this should display in the Android app.

**Protocol**
The actual location sharing is very simple - a normal message with an embedded [geo: URI](https://en.wikipedia.org/wiki/Geo_URI_scheme).
