### ISSUE TITLE
UI issues on iPad

### ISSUE THREAD

**Issue by mimi89999** [snikket-im/snikket-ios#5]
**Describe the bug**
UI issues on iPad.

**To Reproduce**
1. Open Snikket
2. Add an account
3. Join several rooms and add several contacts

**Expected behavior**

**Screenshots**
![IMG_0652](https://user-images.githubusercontent.com/8530546/106795438-5e4b1200-665a-11eb-9a4b-d4cc533f4e8e.PNG)
1. Buttons on the welcome page don't have a background and their label does not have sufficient contrast with the background.
2. The might be too big
3. The app name in the header does not have sufficient contrast

![IMG_0653](https://user-images.githubusercontent.com/8530546/106795442-5f7c3f00-665a-11eb-988f-24a612feda83.PNG)
1. The Chats header seems to be grayed out
2. Contact name overlaps sent date label
3. The input field is too high. That occurs only for MUCs
4. ~The send buttons might be too small~ (edit by MattJ: fixed by #23)
5. MUC name label could be wider

**Details (please complete the following information):**
 - Siskin Version: 1.1 (6) from TestFlight
 - iOS version: 12.5.1
 - iPhone model: iPad Air

**Comment by mwild1** [comment]
I know @zeen started work on this, so temporarily leaving it assigned.

**Comment by mwild1** [comment]
Just re-tested in the simulator, and it looks like the header in the "Chats" page is fixed. The welcome screen issues remain, though. I didn't test groups.

**Comment by mwild1** [comment]
Fixed by https://github.com/snikket-im/snikket-ios/pull/65
