### ISSUE TITLE
Replace Padlock icon indicating omemo encryption in chat view

### ISSUE THREAD

**Issue by sonicnkt** [snikket-im/snikket-ios#58]
In the current iOS beta (1.1 (13) ) the padlock icon indicating omemo encryption looks a bit out of place when compared to the other icons used in the app (line style). 

It seems to be a bit more complicated to fix as the app is currently using an emoji font to display that icon. 

Here is a mockup showing the current icons and a possible new one more inline with the other used icons in the chat view just so everybody knows what i mean :) 
![grafik](https://user-images.githubusercontent.com/5454622/130417337-30351069-83a6-4a01-b19e-4a5f9ec96295.png)

**Comment by mwild1** [comment]
The current implementation (emoji text rendering) will need to be replaced by (a stack of?) icons I think, to cover the possible statuses.
