### ISSUE TITLE
Failure to synchronize MUC bookmarks on iOS

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#6]
**Describe the bug**
The Snikket iOS client fails to display MUCs that the user has been invited to and that appear in the user's bookmarks on the server. Related server issue: https://github.com/snikket-im/snikket-server/issues/16

**To Reproduce**
1. Create new circle via web admin dashboard
2. Invite iOS user to new circle
3. Dismiss or ignore push notification on iOS
4. Observe that user has bookmark to MUC (in `snikket` docker container: `/snikket/prosody/domain/pep_storage/bookmarks`)
5. Observe that MUC does not show up in iOS app chats, contacts or elsewhere

**Expected behavior**
MUCs created when a new circle is created should display in main chat screen on iOS when a user is invited. This is what happens on Android. 

**Details (please complete the following information):**
 - Snikket TestFlight build 1.1
 - Xcode 12.3
 - iPhone SE (2nd generation)

**Comment by mwild1** [comment]
I need to look into this one, it may be fixed. My theory is that it is perhaps related to the general issue with "private" account stanzas that Siskin has with Prosody.

**Comment by mwild1** [comment]
Specifically the thing fixed in this commit: https://github.com/tigase/tigase-swift/commit/ee7b5cea8801b9a621481d0346078dbf30c2970c

It doesn't appear to be released yet.

**Comment by mwild1** [comment]
The commit linked above is now in Tigase-Swift 2.1.2. It should fix a range of subtle issues.

It did not magically solve this issue, however. I tracked this down to the app silently skipping over bookmarks that have no "nick" set. In this case the correct behaviour would be to use a default nick instead (the user's display name).
