### ISSUE TITLE
Hide group 'add members' button when the user does not have permission

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-ios#83]
**Describe the bug**
Confusing error messages appear in a circle's group chat when a non-admin user attempts to add a member.

**To Reproduce**
1. Go to circle's group chat (as non-admin)
2. Tap the plus icon in the upper right
3. Select a user
4. Observe messages in chat shown in screenshot below.

**Expected behavior**
A system error message telling the user they do not have permission to invite members to the group chat would be better than these confusing messages. However, perhaps hiding the plus icon altogether unless they have permission would be simpler and better.

**Screenshots**
![group_error](https://user-images.githubusercontent.com/65571/131874231-2069e369-3566-4d1e-afdc-4d117b207118.png)

**Details (please complete the following information):**
 - App Version: App Store 1.0
 - iOS version: N/A
 - iPhone model: N/A

**Comment by mwild1** [comment]
1. If the user's own room affiliation is *owner* or *admin* then they should always be allowed to invite.
2. If the user's affiliation is *member* or *none* then they can only send an invite if that is permitted by the room configuration.

If none of these things are true, the button to add new users should be hidden.

The app needs to find out if room invites are allowed in the configuration it fetches here: https://github.com/snikket-im/snikket-ios/blob/c0dd98c49e065a551fc8bedb1a8e4fe7096ef3d7/Snikket/groupchat/MucChatSettingsViewController.swift#L356

The Android app checks for `muc#roomconfig_allowinvites` here: https://github.com/snikket-im/snikket-android/blob/69ca6293c76096c6754bbc68091834deb6c1a3d9/src/main/java/eu/siacs/conversations/entities/MucOptions.java#L161

**Comment by mwild1** [comment]
It looks like the user's current affiliation is fetched here: https://github.com/snikket-im/snikket-ios/blob/c0dd98c49e065a551fc8bedb1a8e4fe7096ef3d7/Snikket/groupchat/MucChatSettingsViewController.swift#L122
