### ISSUE TITLE
audio cannot be played when a audio message sent from android phone 

### ISSUE THREAD

**Issue by MuhammedAnasm4444** [snikket-im/snikket-ios#93]
Audio is not playable when messaging from android client
*
 it show doesnt show how much duration is the audio  and it only show "00"  seconds  audio cell.

**Comment by mwild1** [comment]
Hi, thanks for the report!

Unfortunately I can't reproduce this issue. Can you share the app and OS versions of each device?

**Comment by MuhammedAnasm4444** [comment]
I have a android XMPP client  and when I am using with that client audio chat Is not working, but it is working fine in other android XMPP client. I think it is the issue in my android client..

**Comment by mwild1** [comment]
Which client is it on Android?

**Comment by MuhammedAnasm4444** [comment]
I used "conversation" client for my android app. it working fine in real conversation app and but not in my app 'edited' conversation app
