### ISSUE TITLE
No notification on iOS app when receiving media (an image) from an Android device

### ISSUE THREAD

**Issue by andrekrit** [snikket-im/snikket-ios#94]
**Describe the bug**
No notification on iOS app when receiving media (an image) from an Android device. (Not tested from iOS to iOS).

**To Reproduce**
1. For an existing contact (i.e. sender and receiver added to each other's rosters and omemo fingerprints accepted)
2. From Snikket (or Conversations) on Android - send any picture to your contact who is using Snikket on iOS
3. Image is prepared and sent successfully.
4. No notification received on iOS.  (Normal messages do result in notifications)

**Expected behavior**
The iOS Snikket app generates a notification on the iPhone

**Details (please complete the following information):**
 - App Version: [e.g. 1.1]
 - iOS version [e.g. 12.5.3]
 - iPhone model [e.g. iPhone 6]

**Additional context**
This bug was present in SiskinIM. I really hoped it would've been fixed in Snikket!

**Comment by MuhammedAnasm4444** [comment]
Is your audio message working properly when sending a audio message from android to IOS???

**Comment by mwild1** [comment]
Hi, thanks for the report!

Unfortunately I can't reproduce this issue. Is the iOS app connected to a Snikket server?

If yes, can you check the debug information for the affected user in the admin web panel? Particularly the 'push_registrations' fields. Is there data shown there, or are they empty?

**Comment by mwild1** [comment]
I'm closing this issue because I can't reproduce it and there has been no response for a week. Feel free to reply any time and we can reopen it if necessary :)

**Comment by andrekrit** [comment]
My apologies for only replying now. I've been helping out family with funeral arrangements.

Back to the issue at hand. When I noted the problem originally, I was using the Snikket apps on both Android and iOS, but with non-Snikket servers. I've now created new accounts on a Snikket server - one for the iOS device and one for Android - and unfortunately the problem still persists. Sending any media: an image, gif, audio or another document (txt file for example) from the Android app to the iOS app generates **no notification** on the iOS device (Apple iPhone 6 with iOS 12.5.4). The image is delivered and is displayed normally when the app is opened (well, mostly, sometimes it's "squashed", but that issue was inherited from SiskinIM and already mentioned elsewhere), but no notification is received. Sending a simple text message directly afterwards generates a notification as usual.

As requested, I've also checked the debug information. The iOS user is registered for push and has node and service info displayed (push-ios.snikket.net) with an error count of 0.

**Comment by andrekrit** [comment]
I was just testing the avatar functionality on iOS (which didn't work for me previously) and discovered that after publishing an avatar from iOS, push notification for media messages miraculously started working! What in the world could cause this? A very weird case indeed ;-). I'll try it again with a new user tomorrow, but it would be great if someone else could check it out as well.

PS: I'm really stoked about this project's efforts to give XMPP messaging a push forward and to make it more accessible and user friendly. I hope to be able to further contribute to this project in future. There are still a few bugs / missing features which prohibit me from getting more family and friends onboard. The iOS app is my biggest issue at this moment.
